// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<EmbeddingResult> embed({
  required String modelPath,
  required String tokenizerPath,
  required String kind,
  required String text,
}) => RustLib.instance.api.crateApiEmbeddingEmbed(
  modelPath: modelPath,
  tokenizerPath: tokenizerPath,
  kind: kind,
  text: text,
);

class EmbeddingResult {
  final Float32List vector;
  final int dimension;
  final double norm;
  final bool finite;

  const EmbeddingResult({
    required this.vector,
    required this.dimension,
    required this.norm,
    required this.finite,
  });

  @override
  int get hashCode =>
      vector.hashCode ^ dimension.hashCode ^ norm.hashCode ^ finite.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbeddingResult &&
          runtimeType == other.runtimeType &&
          vector == other.vector &&
          dimension == other.dimension &&
          norm == other.norm &&
          finite == other.finite;
}
