// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<MarkdownTypstResult> convertMarkdown({
  required String markdown,
  required String title,
  String? baseUrl,
}) => RustLib.instance.api.crateApiMarkdownImportConvertMarkdown(
  markdown: markdown,
  title: title,
  baseUrl: baseUrl,
);

class MarkdownImportDiagnostic {
  final String code;
  final String message;
  final BigInt? line;

  const MarkdownImportDiagnostic({
    required this.code,
    required this.message,
    this.line,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ line.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarkdownImportDiagnostic &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          line == other.line;
}

class MarkdownTypstResult {
  final String typst;
  final List<MarkdownImportDiagnostic> diagnostics;

  const MarkdownTypstResult({required this.typst, required this.diagnostics});

  @override
  int get hashCode => typst.hashCode ^ diagnostics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarkdownTypstResult &&
          runtimeType == other.runtimeType &&
          typst == other.typst &&
          diagnostics == other.diagnostics;
}
