// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<VaultNoteResult?> convertVaultNote({
  required String dialect,
  required String sourceRelPath,
  required String markdown,
}) => RustLib.instance.api.crateApiVaultImportConvertVaultNote(
  dialect: dialect,
  sourceRelPath: sourceRelPath,
  markdown: markdown,
);

class VaultNoteProperty {
  final String key;
  final String value;

  const VaultNoteProperty({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultNoteProperty &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

class VaultNoteResult {
  final String relPath;
  final String typst;
  final List<String> referencedAssets;
  final List<String> wikilinkTargets;
  final List<String> diagnostics;
  final String id;
  final String title;
  final String kind;
  final String? date;
  final List<String> tags;
  final List<String> aliases;
  final List<VaultNoteProperty> properties;
  final int droppedBlockRefs;
  final int strippedMacros;

  const VaultNoteResult({
    required this.relPath,
    required this.typst,
    required this.referencedAssets,
    required this.wikilinkTargets,
    required this.diagnostics,
    required this.id,
    required this.title,
    required this.kind,
    this.date,
    required this.tags,
    required this.aliases,
    required this.properties,
    required this.droppedBlockRefs,
    required this.strippedMacros,
  });

  @override
  int get hashCode =>
      relPath.hashCode ^
      typst.hashCode ^
      referencedAssets.hashCode ^
      wikilinkTargets.hashCode ^
      diagnostics.hashCode ^
      id.hashCode ^
      title.hashCode ^
      kind.hashCode ^
      date.hashCode ^
      tags.hashCode ^
      aliases.hashCode ^
      properties.hashCode ^
      droppedBlockRefs.hashCode ^
      strippedMacros.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultNoteResult &&
          runtimeType == other.runtimeType &&
          relPath == other.relPath &&
          typst == other.typst &&
          referencedAssets == other.referencedAssets &&
          wikilinkTargets == other.wikilinkTargets &&
          diagnostics == other.diagnostics &&
          id == other.id &&
          title == other.title &&
          kind == other.kind &&
          date == other.date &&
          tags == other.tags &&
          aliases == other.aliases &&
          properties == other.properties &&
          droppedBlockRefs == other.droppedBlockRefs &&
          strippedMacros == other.strippedMacros;
}
